version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - cyclop
    - nestif
    - funlen
    - gocognit
    - prealloc
    - errorlint
    - wrapcheck
    - noctx
    - gosec
    - bodyclose

  settings:
    funlen:
      lines: 80
    cyclop:
      max-complexity: 15
    nestif:
      min-complexity: 5
