version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - cyclop
    - nestif
    - funlen
    - gocognit
    - errorlint
    - gosec
    - bodyclose

  settings:
    funlen:
      lines: 90
      statements: 50
    cyclop:
      max-complexity: 30
    nestif:
      min-complexity: 5
    gocognit:
      min-complexity: 35
    gosec:
      excludes:
        - G101
        - G115
        - G304
