apiVersion: v1
kind: ConfigMap
metadata:
  name: fiber-template-config
  namespace: fiber-template
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  HTTP_LISTEN_ADDRESS: ":8080"
  CORS_ALLOW_ORIGINS: ""
  BODY_LIMIT: "4194304"
  SESSION_DURATION: "24h"
  OTEL_EXPORTER_ENDPOINT: ""
