apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fiber-template
  namespace: fiber-template
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - api.example.com
      secretName: fiber-template-tls
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fiber-template
                port:
                  name: http
